server:
  port: 7072
  servlet:
    context-path: /
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    enable-self-preservation: false      # 关闭自我保护模式（默认为打开）
    eviction-interval-timer-in-ms: 5000  # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
    fetch-registry: true #是否从EurekaServer获取注册信息，单节点可不需要
    register-with-eureka: true #是否将自己注册到EurekaServer
    service-url:
      defaultZone: http://center:center12345!@localhost:7071/eureka
spring:
  application:
    name: item-demo
  datasource:
    url: jdbc:postgresql://rm-2zefzzv3s8d74dyfvho.pg.rds.aliyuncs.com:3432/arnaya_web_dev
    username: aranya_staging
    password: e23TsmZasGyEAqd2018
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted_at
feign:
  mall: item-mall
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000